services:
  extended-setup-api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: pydaadop-quick-example-api
    ports:
      - 8000:8000
    env_file:
      - example.env
    networks:
      - pydaadop-quick-example-network

  quick-setup-mongo:
    image: mongo:latest
    command: mongod --port ${MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    container_name: pydaadop-quick-example-mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"  # Expose MongoDB on port
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    networks:
      - pydaadop-quick-example-network

volumes:
  mongo_data: # Define a named volume for MongoDB data persistence

networks:
  pydaadop-quick-example-network:
    driver: bridge  # Define the network with a driver