services:
  mongo:
    image: mongo:latest
    command: mongod --port ${MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    container_name: pydaadop-mongo-example
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"  # Expose MongoDB on port 27017
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    networks:
      - pydaadop-example-network  # Shared network

volumes:
  mongo_data:  # Define a named volume for MongoDB data persistence

networks:
  pydaadop-example-network:
    external: true  # Use the same external network
