- SETUP_NAME: quick-setup
  FILE_MAPPINGS: |
    example.env:examples/setups/quick/example.env
    api.py:examples/setups/quick/api.py
    docker-compose.yml:examples/quick/docker-compose.yml
    api.Dockerfile:examples/quick/api.Dockerfile
    requirements.txt:examples/requirements.txt

- SETUP_NAME: extended-setup
  FILE_MAPPINGS: |
    example.env:examples/setups/extended/example.env
    api.py:examples/setups/extended/api.py
    init.py:examples/setups/extended/init.py
    docker-compose.yml:examples/extended/docker-compose.yml
    api.Dockerfile:examples/extended/api.Dockerfile
    init.Dockerfile:examples/extended/init.Dockerfile
    requirements.txt:examples/requirements.txt
    custom_model.py:examples/models/custom_model.py
    generic_model.py:examples/models/generic_model.py
    my_definition.py:examples/models/my_definition.py
