services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        FAST_API_BASE_URL: ${FAST_API_BASE_URL}
        FAST_API_PORT: ${FAST_API_PORT}
    container_name: pydaadop-api-example
    ports:
      - "${FAST_API_PORT}:${FAST_API_PORT}"
    env_file:
      - example.env
    networks:
      - pydaadop-example-network

  mongo:
    image: mongo:latest
    command: mongod --port ${MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    container_name: pydaadop-mongo-example
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"  # Expose MongoDB on port
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    networks:
      - pydaadop-example-network  # Shared network

  init:
    build:
      context: .
      dockerfile: init.Dockerfile  # Assuming the custom Dockerfile is named Dockerfile
    depends_on:
      - api
    env_file:
      - example.env
    networks:
      - pydaadop-example-network  # Shared network
    restart: "no"  # Ensure this service doesn't restart unnecessarily

volumes:
  mongo_data: # Define a named volume for MongoDB data persistence

networks:
  pydaadop-example-network:
    driver: bridge  # Define the network with a driver