site_name: PyDaaDop Documentation
theme:
  name: material
  features:
    - navigation.tabs

nav:
  - Home: index.md
  - Get Started: get-started.md
  - Concepts: concepts.md
  - API Documentation: api.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
