name: Auto Setup Release

on:
  push:
    branches:
      - main
    paths:
      - 'examples/**'
jobs:
  release:
    name: Create Quick Setup Release
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository from main (full history for tags)
      - name: Checkout repository from main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # 2. Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # 3. Determine the next release tag (format: quick-setup-vX)
      - name: Determine Next Release Tag
        id: tag
        run: |
          NEXT_TAG="quick-setup-release"
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
          echo "Next release tag: $NEXT_TAG"

      # 4. Copy the desired files from the main branch into a temporary folder outside the repo
      - name: Copy release files to temporary folder
        run: |
          mkdir -p /tmp/release-files
          cp examples/example.env /tmp/release-files/example.env
          cp examples/setups/quick/api.py /tmp/release-files/api.py
          cp examples/setups/quick/client.py /tmp/release-files/client.py
          cp examples/requirements.txt /tmp/release-files/requirements.txt
          cp examples/docker-compose.yml /tmp/release-files/docker-compose.yml

      # 5. Switch to (or create) the quick-setup branch
      - name: Switch to or create quick-setup branch
        run: |
          if git show-ref --verify --quiet refs/heads/quick-setup; then
            echo "Branch exists, switching..."
            git checkout quick-setup
          else
            echo "Branch does not exist, creating..."
            git checkout -b quick-setup
          fi

      # 6. Empty the quick-setup branch
      - name: Delete all files in quick-setup branch
        run: |
          git rm -rf . || true
          git commit -m "Cleanup quick-setup branch" || echo "No files to remove"

      # 7. Copy the files from the temporary folder into the root of the branch
      - name: Copy files from temporary folder into branch root
        run: |
          cp /tmp/release-files/example.env .
          cp /tmp/release-files/api.py .
          cp /tmp/release-files/client.py .
          cp /tmp/release-files/requirements.txt .
          cp /tmp/release-files/docker-compose.yml .
          rm -rf /tmp/release-files  # Remove temporary folder after copying

      # 8. Commit and push the new files to quick-setup branch
      - name: Commit new files in quick-setup branch
        run: |
          git add example.env api.py client.py requirements.txt docker-compose.yml
          git commit --allow-empty -m "Prepare Quick Setup release"
          git push origin quick-setup --force

      # 9. Create and push the new tag (quick-setup-vX) if it does not already exist
      - name: Create and Push New Tag
        run: |
          if git rev-parse "$NEXT_TAG" >/dev/null 2>&1; then
            echo "Tag $NEXT_TAG already exists"
          else
            git tag $NEXT_TAG
            git push origin $NEXT_TAG
          fi

      # 10. Create a GitHub Release using the new tag
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEXT_TAG }}
          name: Quick Setup Release ${{ env.NEXT_TAG }}
          body: "Automated release for Quick Setup."
          files: example.env, api.py, client.py, requirements.txt, docker-compose.yml
          target_commitish: quick-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
