name: Auto Setup Release

on:
  push:
    branches:
      - main


jobs:
  release:
    name: Create Quick Setup Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Prepare files (before switching branch)
        run: |
          cp examples/example.env example.env
          cp examples/setups/quick/api.py api.py
          cp examples/setups/quick/client.py client.py
          cp examples/requirements.txt requirements.txt
          cp examples/docker-compose.yml docker-compose.yml

      - name: Stash prepared files
        run: |
          git add example.env api.py client.py requirements.txt docker-compose.yml
          git stash push -m "Stashing quick-setup files"

      - name: Check if branch exists and create if necessary
        run: |
          if git show-ref --verify --quiet refs/heads/quick-setup; then
            echo "Branch exists, switching..."
            git checkout quick-setup
          else
            echo "Branch does not exist, creating..."
            git checkout -b quick-setup
          fi

      - name: Delete all files in branch
        run: |
          git rm -rf . || true  # Remove all files (ignore errors)
          git commit -m "Cleanup quick-setup branch" || echo "No changes to commit"

      - name: Apply stashed files
        run: |
          git stash pop || echo "No stash found, skipping"

      - name: Commit new files
        run: |
          git add example.env api.py client.py requirements.txt docker-compose.yml
          git commit -m "Prepare Quick Setup release"
          git push origin quick-setup --force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: quick-setup
          name: Quick Setup Release ${{ github.sha }}
          body: "Automated release for Quick Setup."
          files: example.env api.py client.py requirements.txt docker-compose.yml
          target_commitish: quick-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
