name: Auto Setup Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Quick Setup Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches and tags

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Determine Next Release Tag
        id: tag
        run: |
          # Get the latest quick-setup-v* tag, extract the number, and increment it
          LATEST_TAG=$(git tag -l "quick-setup-v*" | sort -V | tail -n 1)
          if [[ -z "$LATEST_TAG" ]]; then
            NEXT_TAG="quick-setup-v1"
          else
            TAG_NUMBER=$(echo "$LATEST_TAG" | grep -o '[0-9]*$')
            NEXT_NUMBER=$((TAG_NUMBER + 1))
            NEXT_TAG="quick-setup-v$NEXT_NUMBER"
          fi
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
          echo "Next release tag: $NEXT_TAG"

      - name: Check if branch exists and create if necessary
        run: |
          if git show-ref --verify --quiet refs/heads/quick-setup; then
            echo "Branch exists, switching..."
            git checkout quick-setup
          else
            echo "Branch does not exist, creating..."
            git checkout -b quick-setup
          fi

      - name: Delete all files in branch
        run: |
          git rm -rf . || true  # Remove all files (ignore errors)
          git commit -m "Cleanup quick-setup branch" || echo "No changes to commit"

      - name: Copy files directly to root
        run: |
          cp examples/example.env .
          cp examples/setups/quick/api.py .
          cp examples/setups/quick/client.py .
          cp examples/requirements.txt .
          cp examples/docker-compose.yml .

      - name: Commit new files in root
        run: |
          git add example.env api.py client.py requirements.txt docker-compose.yml
          git commit -m "Prepare Quick Setup release"
          git push origin quick-setup --force

      - name: Create and Push New Tag
        run: |
          git tag $NEXT_TAG
          git push origin $NEXT_TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEXT_TAG }}
          name: Quick Setup Release ${{ env.NEXT_TAG }}
          body: "Automated release for Quick Setup."
          files: example.env, api.py, client.py, requirements.txt, docker-compose.yml
          target_commitish: quick-setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
