name: Auto Setup Release

on:
  push:
    branches:
      - main
    paths:
      - 'examples/configuration.yml'
      - 'examples/**'
      - '.github/workflows/auto_setup_release_generic.yml'

jobs:
  # ─── JOB 1: Generate the matrix from configuration ─────────────────────────────
  generate-matrix:
    name: Generate Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install PyYAML

      - name: Generate matrix from configuration file
        id: set-matrix
        run: |
          python - << 'EOF'
          import yaml, json, sys
          try:
              with open('examples/configuration.yml', 'r') as f:
                  # The configuration file is expected to be a YAML list
                  configs = yaml.safe_load(f)
          except Exception as e:
              sys.exit(f"Failed to load configuration: {e}")

          matrix = {"include": []}
          for conf in configs:
              # Each block must have SETUP_NAME and FILE_MAPPINGS keys.
              setup_name = conf.get("SETUP_NAME")
              file_mappings = conf.get("FILE_MAPPINGS")
              if not setup_name or not file_mappings:
                  sys.exit("Each configuration block must include SETUP_NAME and FILE_MAPPINGS")
              matrix["include"].append({
                  "setup_name": setup_name,
                  "file_mappings": file_mappings
              })
          print("::set-output name=matrix::" + json.dumps(matrix))
          EOF
  # ─── JOB 2: Process each setup from the matrix ─────────────────────────────
  release:
    name: Create Release per Setup
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Display setup info
        run: |
          echo "Processing setup: ${{ matrix.setup_name }}"
          echo "File mappings:"
          echo "${{ matrix.file_mappings }}"

      # ─── Determine next release tag ─────────────────────────────
      - name: Determine Next Release Tag
        id: tag
        run: |
          SETUP_NAME="${{ matrix.setup_name }}"
          BASE_TAG="${SETUP_NAME}-v"
          # Find the latest tag that starts with the base tag
          LATEST=$(git tag --list "${BASE_TAG}*" | sort -V | tail -n1)
          if [ -z "$LATEST" ]; then
            NEXT_TAG="${BASE_TAG}1"
          else
            NUM=${LATEST##*-v}
            NEXT_TAG="${BASE_TAG}$((NUM + 1))"
          fi
          echo "Next tag: $NEXT_TAG"
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV

      # ─── Copy files to a temporary folder using file mappings ─────────────
      - name: Copy release files to temporary folder
        run: |
          mkdir -p /tmp/release-files
          # Process each line of file mappings (delimiter is a colon)
          echo "${{ matrix.file_mappings }}" | while IFS=: read -r dest src; do
            # Skip empty lines
            [ -z "$dest" ] && continue
            echo "Copying $src to /tmp/release-files/$dest"
            cp "$src" "/tmp/release-files/$dest"
          done

      # ─── Switch to (or create) branch for the setup ─────────────
      - name: Switch to or create setup branch
        run: |
          SETUP_BRANCH="${{ matrix.setup_name }}"
          if git show-ref --verify --quiet refs/heads/${SETUP_BRANCH}; then
            echo "Branch exists, switching to ${SETUP_BRANCH}..."
            git checkout ${SETUP_BRANCH}
          else
            echo "Branch does not exist. Creating ${SETUP_BRANCH}..."
            git checkout -b ${SETUP_BRANCH}
          fi

      # ─── Delete all existing files in the branch ─────────────
      - name: Clean branch files
        run: |
          git rm -rf . || true
          git commit -m "Cleanup ${SETUP_BRANCH} branch" || echo "No files to remove"

      # ─── Copy files from temporary folder into branch root ─────────────
      - name: Copy files from temporary folder into branch root
        run: |
          echo "${{ matrix.file_mappings }}" | while IFS=: read -r dest _; do
            [ -z "$dest" ] && continue
            echo "Copying /tmp/release-files/$dest to ./$dest"
            cp "/tmp/release-files/$dest" "./$dest"
          done
          rm -rf /tmp/release-files

      # ─── Commit and push the new files ─────────────
      - name: Commit and push files to branch
        run: |
          # Extract destination filenames and add them to Git.
          files=$(echo "${{ matrix.file_mappings }}" | awk -F: '{print $1}' | paste -sd " " -)
          echo "Files to add: $files"
          git add $files
          git commit --allow-empty -m "Prepare ${{ matrix.setup_name }} release"
          git push origin "${{ matrix.setup_name }}" --force

      # ─── Create (or update) the tag for this setup ─────────────
      - name: Create and Push New Tag
        run: |
          if git rev-parse "$NEXT_TAG" >/dev/null 2>&1; then
            echo "Tag $NEXT_TAG already exists"
          else
            git tag "$NEXT_TAG"
            git push origin "$NEXT_TAG"
          fi

      # ─── Generate comma-separated asset list from file mappings ─────────────
      - name: Generate asset file list
        id: assets
        run: |
          asset_files=$(echo "${{ matrix.file_mappings }}" | awk -F: '{print $1}' | paste -sd, -)
          echo "Asset files: $asset_files"
          echo "asset_files=$asset_files" >> "$GITHUB_OUTPUT"

      # ─── Create GitHub Release with assets ─────────────
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEXT_TAG }}
          name: "${{ env.NEXT_TAG }}"
          body: "Automated release for ${{ matrix.setup_name }}"
          files: ${{ steps.assets.outputs.asset_files }}
          target_commitish: ${{ matrix.setup_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
