name: Create Tag from Commit Message with Incremented Version

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags are fetched

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get commit message and determine tag
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit Message: $COMMIT_MSG"
          
          if [[ "$COMMIT_MSG" =~ ^[[:space:]]*Release:[[:space:]]*quick-setup ]]; then
            TAG_PREFIX="quick-setup"
          elif [[ "$COMMIT_MSG" =~ ^[[:space:]]*Release:[[:space:]]*doc-update ]]; then
            TAG_PREFIX="doc-update"
          else
            echo "No release prefix found in commit message. Skipping tag creation."
            exit 0
          fi

          LAST_TAG=$(git tag -l "${TAG_PREFIX}-v*" | sort -V | tail -n 1)

          if [[ -z "$LAST_TAG" ]]; then
            VERSION="v1.0.0"
          else
            VERSION=$(echo $LAST_TAG | sed -E 's/.*-v([0-9]+\.[0-9]+\.[0-9]+)$/\1/')
            VERSION=$(echo $VERSION | awk -F. -v OFS=. '{$NF++; print $0}')
          fi

          NEW_TAG="${TAG_PREFIX}-${VERSION}"
          echo "Creating new tag: $NEW_TAG"

          git tag -a "$NEW_TAG" -m "Auto-generated tag"
          git push origin "$NEW_TAG"
